### PR TITLE
create react app

### PR DESCRIPTION
**Pull request by edgardsoza**
React app created. 
README file properly set. 
Gitflow was used properly
App working without issues

### CODE REVIEW

**Review by addod19 — CHANGES_REQUESTED** [review]
### Hi @edgardsoza, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [ ] Correct Git-flow followed :
- [ ] App create with `create-react-app`


## Required Changes ♻️
_Check the comments under the review._
- [ ] It would be better if we fix the MIT license link because it is broken and it redirects us to 404 pagelet us kindly fix it
- [ ] It would be better if we add node_modules to our gitignore file, this made our file changes over 5000 and making the review difficult and time consuming


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by edgardsoza** [comment]
@addod19  quick question, if I ignore the node modules, I got a linter error that says react_app was not found, what should I do then?

**Comment by addod19** [comment]
> @addod19 quick question, if I ignore the node modules, I got a linter error that says react_app was not found, what should I do then?

@edgardsoza, alright but I wanted you to know how the huge number of file changes interferes with the reviews.

**Comment by edgardsoza** [comment]
> > @addod19 quick question, if I ignore the node modules, I got a linter error that says react_app was not found, what should I do then?
> 
> @edgardsoza, alright but I wanted you to know how the huge number of file changes interferes with the reviews.
I am working on it, not sure what should I try

**Pull request closed without merging**
